# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CapstoneProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'NMapsMap'
  pod 'SnapKit'
  pod 'Then'

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Pods for CapstoneProject

end
